webtalk_init -webtalk_dir D:/FPGA/MiniSys/MiniSys.sim/sim_1/behav/xsim.dir/line_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 01 12:00:48 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "204274020_0_0_646" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "36d68f3c863151b6ae7f5bb5b48a814f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bf4d60825a14418bb25d40e51d870108" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "44" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "620 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "80 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "2174" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1726" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "434" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.61_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "111724_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2922141399 -regid "204274020_0_0_646" -xml D:/FPGA/MiniSys/MiniSys.sim/sim_1/behav/xsim.dir/line_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/FPGA/MiniSys/MiniSys.sim/sim_1/behav/xsim.dir/line_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/FPGA/MiniSys/MiniSys.sim/sim_1/behav/xsim.dir/line_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
