# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/MiniSys/MiniSys.cache/wt [current_project]
set_property parent.project_path D:/FPGA/MiniSys/MiniSys.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/FPGA/MiniSys/MiniSys.srcs/sources_1/test_dmem32.coe
add_files D:/FPGA/MiniSys/MiniSys.srcs/sources_1/rom.coe
read_ip -quiet D:/FPGA/MiniSys/MiniSys.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/MiniSys/MiniSys.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files D:/FPGA/MiniSys/MiniSys.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_ip -quiet D:/FPGA/MiniSys/MiniSys.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/FPGA/MiniSys/MiniSys.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files D:/FPGA/MiniSys/MiniSys.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci]

read_verilog -library xil_defaultlib {
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/g_p.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/add.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/cla_2.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/cla_4.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/cla_8.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/cla_16.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/cla_32.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/cla32.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/imports/new/clockDiv.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/dev_leds.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/imports/new/dev_beep.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/dev_switches.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/devices/dev_timer.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/devices/dev_segment.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/devices/dev_pwm.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/devices/dev_keyboard.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/shift.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/mux8x32.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/alucontrol.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/addsub32.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/mux4x32.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/dffe32.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipedevices.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipeimem.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/regfile.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipemem.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipeidcu.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipeidcp.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/mux2x5.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/mux2x32.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/alu.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipepc.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipeif.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipemwreg.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipeir.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipeid.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipeexe.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipeemreg.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipedereg.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/MemorIo.v
  D:/FPGA/MiniSys/MiniSys.srcs/sources_1/new/pipelinedcpu.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/MiniSys/MiniSys.srcs/constrs_1/new/xdc1.xdc
set_property used_in_implementation false [get_files D:/FPGA/MiniSys/MiniSys.srcs/constrs_1/new/xdc1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top pipelinedcpu -part xc7a100tfgg484-1


write_checkpoint -force -noxdef pipelinedcpu.dcp

catch { report_utilization -file pipelinedcpu_utilization_synth.rpt -pb pipelinedcpu_utilization_synth.pb }
